- hosts: jenkins_ec2
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    

    - name: Pull nginx container
      docker_container:
        name: webapp
        image: nginx:latest
        state: started
        ports:
          - "80:80"

